image: node:12

stages:
  - test
  - build
  - deploy

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build

unit test:
  stage: test
  script:
    - npm run lint
    - npm run test
  artifacts:
    paths:
      - node_modules/
      - package.json
      - package-lock.json
