image: node:10.15.0

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build

unit test:
  stage: test
  script:
    - npm run lint
    - npm run test
  artifacts:
    paths:
      - dist/
      - node_modules/
      - package.json


publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --dry-run